name: doctorsoft_storage
description: Armazenamento seguro dos tokens do usuário no dispositivo.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_secure_storage: ^7.0.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.16.4
  very_good_analysis: ^3.0.2