name: doctor_soft_angola_api
description: A Dart API Client for the Specialties API.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.0
  json_annotation: ^4.6.0
  dio: ^4.0.6
  connectivity_plus: ^3.0.2
  doctorsoft_storage:
    path: ../storage
  patient_repository:
    path: ../repositories/patient_repository
  medic_repository:
    path: ../repositories/medic_repository
  authentication_repository:
    path: ../repositories/authentication_repository

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  test: ^1.16.4
  very_good_analysis: ^3.0.2